
    
platform :ios, '11.0'

target 'Test App iOS' do
  use_frameworks!

# Pods for Alamofire
  pod 'Alamofire'
  
  target 'Test App iOSTests' do
    use_frameworks!
    inherit! :search_paths
  end
  
end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
